import Vue from 'vue'
import { Button, Input,Form,FormItem, Breadcrumb, BreadcrumbItem, Pagination,Carousel, CarouselItem,Row,Col,Card,InputNumber,Table,TableColumn,Image,Calendar,MessageBox,Popconfirm, Empty, Menu,Submenu,MenuItem,Icon} from 'element-ui'

Vue.use(Button)
Vue.use(Input)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Row)
Vue.use(Col)
Vue.use(Card)
Vue.use(Pagination)
Vue.use(InputNumber)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Image)
Vue.use(Calendar)
Vue.use(Popconfirm)
Vue.use(Empty)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(Icon)
Vue.prototype.$mb = MessageBox